# Generated by Django 4.1.7 on 2023-04-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_id',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
