# Generated by Django 4.1.7 on 2023-04-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_courses_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.CharField(max_length=255),
        ),
    ]
